import Foundation

/// Keeps command-owned state inside the command directory.
///
/// Path strings are validated elsewhere. This policy handles the filesystem
/// state those strings cannot express, chiefly symlinks introduced by copied
/// or externally edited command folders.
enum CommandDirectoryPolicy {

    enum Violation: Error, Equatable, LocalizedError {
        case symbolicLink(String)
        case escapesDirectory(String)
        case unexpectedItemType(String)

        var errorDescription: String? {
            switch self {
            case .symbolicLink(let path):
                return "command-owned path is a symbolic link: \(path)"
            case .escapesDirectory(let path):
                return "command-owned path escapes the command directory: \(path)"
            case .unexpectedItemType(let path):
                return "command-owned path has an unexpected type: \(path)"
            }
        }
    }

    private static let dataName = "data"
    private static let storageName = "storage.json"

    /// Returns the lexical `data/` URL after proving that any existing item
    /// is a real directory within the canonical command root.
    static func validatedDataDirectory(
        in commandDirectory: URL
    ) throws -> URL {
        let commandDirectory = commandDirectory.standardizedFileURL
        let dataDirectory = commandDirectory
            .appendingPathComponent(dataName, isDirectory: true)
            .standardizedFileURL

        guard !isSymbolicLink(dataDirectory) else {
            throw Violation.symbolicLink(dataName)
        }
        var dataIsDirectory: ObjCBool = false
        if FileManager.default.fileExists(
            atPath: dataDirectory.path,
            isDirectory: &dataIsDirectory), !dataIsDirectory.boolValue {
            throw Violation.unexpectedItemType(dataName)
        }

        let canonicalRoot = commandDirectory
            .resolvingSymlinksInPath()
            .standardizedFileURL
        let canonicalData = dataDirectory
            .resolvingSymlinksInPath()
            .standardizedFileURL
        guard isDescendant(canonicalData, of: canonicalRoot) else {
            throw Violation.escapesDirectory(dataName)
        }

        return dataDirectory
    }

    /// Rejects symlinks in command-relative write paths. The Maker calls this
    /// before snapshotting or writing so existing filesystem objects cannot
    /// redirect generated bytes outside the command directory.
    static func validateWriteDestinations<Paths: Sequence>(
        in commandDirectory: URL,
        relativePaths: Paths
    ) throws where Paths.Element == String {
        let commandDirectory = commandDirectory.standardizedFileURL
        if isSymbolicLink(commandDirectory) {
            throw Violation.symbolicLink(".")
        }
        let canonicalRoot = commandDirectory
            .resolvingSymlinksInPath()
            .standardizedFileURL

        for relativePath in relativePaths {
            var candidate = commandDirectory
            for component in relativePath.split(separator: "/") {
                candidate.appendPathComponent(String(component))
                if isSymbolicLink(candidate) {
                    throw Violation.symbolicLink(relativePath)
                }
            }

            let canonicalCandidate = candidate
                .resolvingSymlinksInPath()
                .standardizedFileURL
            guard isDescendant(canonicalCandidate, of: canonicalRoot) else {
                throw Violation.escapesDirectory(relativePath)
            }
        }
    }

    /// Returns `data/storage.json` after validating both path components.
    static func validatedStorageURL(
        in commandDirectory: URL
    ) throws -> URL {
        let dataDirectory = try validatedDataDirectory(in: commandDirectory)
        let storageURL = dataDirectory
            .appendingPathComponent(storageName)
            .standardizedFileURL

        let relativeStoragePath = "\(dataName)/\(storageName)"
        guard !isSymbolicLink(storageURL) else {
            throw Violation.symbolicLink(relativeStoragePath)
        }
        if FileManager.default.fileExists(atPath: storageURL.path) {
            let attributes = try FileManager.default.attributesOfItem(
                atPath: storageURL.path)
            guard attributes[.type] as? FileAttributeType == .typeRegular else {
                throw Violation.unexpectedItemType(relativeStoragePath)
            }
        }

        let canonicalData = dataDirectory
            .resolvingSymlinksInPath()
            .standardizedFileURL
        let canonicalStorage = storageURL
            .resolvingSymlinksInPath()
            .standardizedFileURL
        guard isDescendant(canonicalStorage, of: canonicalData) else {
            throw Violation.escapesDirectory("\(dataName)/\(storageName)")
        }

        return storageURL
    }

    /// `fileExists` follows links and misses broken ones. Asking for the
    /// destination identifies the link itself without dereferencing it.
    private static func isSymbolicLink(_ url: URL) -> Bool {
        (try? FileManager.default.destinationOfSymbolicLink(atPath: url.path)) != nil
    }

    private static func isDescendant(_ candidate: URL, of directory: URL) -> Bool {
        let parent = directory.path
        let prefix = parent == "/" ? "/" : parent + "/"
        return candidate.path.hasPrefix(prefix)
    }
}
